version: '3.7'

services:
  api-tests:
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        - POETRY_GROUP=api
    image: chat-widget-qa-task:api
    volumes:
      - ./:/app
    command: |
      bash -c "poetry run pytest -s api_tests/tests --alluredir=allure-results -p no:warnings && touch /app/.api-tests-completed"
    working_dir: /app

  e2e-tests:
    build:
      context: .
      dockerfile: e2e.Dockerfile
      args:
        - POETRY_GROUP=e2e
    image: chat-widget-qa-task:e2e
    volumes:
      - ./:/app
    depends_on:
      - api-tests
    command: |
      bash -c "while [ ! -f /app/.api-tests-completed ]; do echo 'Waiting for api-tests to finish...'; sleep 2; done && poetry run pytest -s e2e_tests/tests --alluredir=allure-results -p no:warnings"
    working_dir: /app